name: Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/.cypress

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Node.js Version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Restore Cypress Binary
        uses: actions/cache@v3
        with:
          path: .cypress
          key: cypress-binary-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile --prefer-offline
          yarn --silent cypress info
          yarn --silent cypress cache list

      # Turborepo attempts to run as many tasks as possible over all available CPU's.
      # This causes problems when multiple Cypress tasks run concurrently as each tries
      # to instantiate xvfb and only one can do so. The solution is to start the process
      # beforehand and set the DISPLAY environment variable which stops Cypress from
      # attempting to instantiate xvfb itself. Multiple processes of Cypress can share
      # the same instance of xvfb.
      - name: Run Package(s) Tests
        run: |
          Xvfb :99 & export DISPLAY=:99
          echo ---
          npx cypress info
          echo ---
          node -p 'os.cpus()'
          echo ---
          yarn run test
